server:
  port: 8000

eureka:
  client:
    rigister-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application: 
    name: gateway
